name: nlw_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1
  http: ^0.12.1
  http_interceptor: ^0.3.1
  path:
  flutter_open_whatsapp: ^0.1.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Archivo
      fonts:
        - asset: fonts/archivo/Archivo-Regular.ttf
        - asset: fonts/archivo/Archivo-SemiBold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf

